version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${APP_TZ:-Asia/Tokyo}
    ports:
      - target: 80
        published: ${DOCKER_WEB_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./
        target: /work/backend

  mysql:
    build:
      context: ./docker/mysql
    volumes:
      - ./docker/log/mysql:/var/log/mysql
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${APP_TZ}
    ports:
      - target: 3306
        published: ${DOCKER_DB_PORT:-3306}
        protocol: tcp
        mode: host

  swagger:
    build:
      context: ./docker/swagger
    volumes:
      - ./docs/swagger/api.yaml:/usr/share/nginx/html/api.yaml
      - ./public/docs:/tmp/dump/html
    environment:
      API_URL: api.yaml
    ports:
      - 801:80
      - 8010:8080

  mailhog:
    image: mailhog/mailhog

  mail:
    build:
      context: ./docker/mail
    hostname: ${MAIL_HOSTNAME}
    domainname: ${MAIL_DOMAINNAME}
    # 実際に飛ばすために Google の DNS と接続
    dns: 8.8.8.8
    ports:
      - 25:25
      - 587:587
    volumes:
      - maildata:/var/mail
    env_file:
      - .env
      - env-mailserver
    cap_add:
      - SYS_PTRACE

volumes:
  db-store:
  maildata:
