<?php

namespace App\ConstantValues;

class Location
{
    public const HOKKAIDO   = 1;
    public const AOMORI     = 2;
    public const IWATE      = 3;
    public const MIYAGI     = 4;
    public const AKITA      = 5;
    public const YAMAGATA   = 6;
    public const FUKUSHIMA  = 7;
    public const IBARAKI    = 8;
    public const TOCHIGI    = 9;
    public const GUNMA      = 10;
    public const SAITAMA    = 11;
    public const CHIBA      = 12;
    public const TOKYO      = 13;
    public const KANAGAWA   = 14;
    public const NIIGATA    = 15;
    public const TOYAMA     = 16;
    public const ISHIKAWA   = 17;
    public const FUKUI      = 18;
    public const YAMANASHI  = 19;
    public const NAGANO     = 20;
    public const GIFU       = 21;
    public const SHIZUOKA   = 22;
    public const AICHI      = 23;
    public const MIE        = 24;
    public const SHIGA      = 25;
    public const KYOTO      = 26;
    public const OSAKA      = 27;
    public const HYOGO      = 28;
    public const NARA       = 29;
    public const WAKAYAMA   = 30;
    public const TOTTORI    = 31;
    public const SHIMANE    = 32;
    public const OKAYAMA    = 33;
    public const HIROSHIMA  = 34;
    public const YAMAGUCHI  = 35;
    public const TOKUSHIMA  = 36;
    public const KAGAWA     = 37;
    public const EHIME      = 38;
    public const KOCHI      = 39;
    public const FUKUOKA    = 40;
    public const SAGA       = 41;
    public const NAGASAKI   = 42;
    public const KUMAMOTO   = 43;
    public const OITA       = 44;
    public const MIYAZAKI   = 45;
    public const KAGOSHIMA  = 46;
    public const OKINAWA    = 47;
    public const PREF_NAMES = [
        self::HOKKAIDO  => '北海道',
        self::AOMORI    => '青森県',
        self::IWATE     => '岩手県',
        self::MIYAGI    => '宮城県',
        self::AKITA     => '秋田県',
        self::YAMAGATA  => '山形県',
        self::FUKUSHIMA => '福島県',
        self::IBARAKI   => '茨城県',
        self::TOCHIGI   => '栃木県',
        self::GUNMA     => '群馬県',
        self::SAITAMA   => '埼玉県',
        self::CHIBA     => '千葉県',
        self::TOKYO     => '東京都',
        self::KANAGAWA  => '神奈川県',
        self::NIIGATA   => '新潟県',
        self::TOYAMA    => '富山県',
        self::ISHIKAWA  => '石川県',
        self::FUKUI     => '福井県',
        self::YAMANASHI => '山梨県',
        self::NAGANO    => '長野県',
        self::GIFU      => '岐阜県',
        self::SHIZUOKA  => '静岡県',
        self::AICHI     => '愛知県',
        self::MIE       => '三重県',
        self::SHIGA     => '滋賀県',
        self::KYOTO     => '京都府',
        self::OSAKA     => '大阪府',
        self::HYOGO     => '兵庫県',
        self::NARA      => '奈良県',
        self::WAKAYAMA  => '和歌山県',
        self::TOTTORI   => '鳥取県',
        self::SHIMANE   => '島根県',
        self::OKAYAMA   => '岡山県',
        self::HIROSHIMA => '広島県',
        self::YAMAGUCHI => '山口県',
        self::TOKUSHIMA => '徳島県',
        self::KAGAWA    => '香川県',
        self::EHIME     => '愛媛県',
        self::KOCHI     => '高知県',
        self::FUKUOKA   => '福岡県',
        self::SAGA      => '佐賀県',
        self::NAGASAKI  => '長崎県',
        self::KUMAMOTO  => '熊本県',
        self::OITA      => '大分県',
        self::MIYAZAKI  => '宮崎県',
        self::KAGOSHIMA => '鹿児島県',
        self::OKINAWA   => '沖縄県',
    ];
}
