<?php


namespace App\Models\Search\MemberAPI;


use App\Models\Search\BaseQueryBuilder\BaseSearchQueryBuilder;
use Illuminate\Database\Query\Builder;

class UserSearchQueryBuilder extends BaseSearchQueryBuilder
{
    protected function select(): array
    {
        // TODO: Implement select() method.
    }

    protected function formatter(object $searchResultItem): object | array
    {
        return parent::formatter($searchResultItem); // TODO: Change the autogenerated stub
    }

    protected function from(): Builder
    {
        // TODO: Implement from() method.
    }

    protected function searchableWhereFields(): array
    {
        // TODO: Implement searchableWhereFields() method.
    }

    protected function orderByAbleFields(): array
    {
        // TODO: Implement orderByAbleFields() method.
    }
}
