<?php

namespace App\Providers;

use Psr\EventDispatcher\EventDispatcherInterface;
use Psr\Log\LoggerInterface;
use Symfony\Component\Mailer\Envelope;
use Symfony\Component\Mailer\SentMessage;
use Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport;
use Symfony\Component\Mailer\Transport\Smtp\SmtpTransport;
use Symfony\Component\Mailer\Transport\Smtp\Stream\AbstractStream;
use Symfony\Component\Mime\RawMessage;

class ISO2022Transport extends EsmtpTransport
{
    public function send(RawMessage $message, Envelope $envelope = null): ?SentMessage
    {
        dump(self::class);
        dd($message->getMessage()->toString());
        return parent::send($message, $envelope); // TODO: Change the autogenerated stub
    }

    protected function doSend(SentMessage $message): void
    {
        dump(self::class);
        dd($message->getMessage()->toString());

        parent::doSend($message);
    }
}
